##
## This is a sample Database schema definition configuration.
##

##
## Version defines the configuration version.
##
version = 1

##
## Schema defines the settings used for locating
## the migration files that form the database
## schema desired state.
##
[schema]
    ## Directory defines the directory path to the
    ## SQL migration files.
    directory = "./sql"
    ## Sequence defines the list of migration files
    ## names that must be executed in the order of
    ## their appearance.
    sequence = [
        "base.sql",
        "roles.sql",
        "user.sql"
    ]
